#!/bin/bash

set -e
if [ "$#" -lt 1 ]; then
  echo "usage: $0 [ -n <namespace> | -c <container> | -w ] <app> <curl_params|url> "
  exit 1
fi
CONTAINER=""
HTTP_CLIENT=curl
while getopts ":c:n:w" opt; do
  case $opt in
    n)
      NAMESPACE=${OPTARG}
      ;;
    c)
      CONTAINER=${OPTARG}
      ;;
    w)
      HTTP_CLIENT="wget -O -"
      ;;
    *)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

shift $((OPTIND-1))
APP=$1
shift
URL=$@
if [ "$URL" == "" ] ; then
  echo "usage: $0 [ -w | -n <namespace> | -c <container> ] <app> <curl_params|url> "
  exit 1
fi

if [ -n "$NAMESPACE" ] ; then
  NAMESPACE_ARGS="-n $NAMESPACE"
fi

POD=$(kubectl get pods $NAMESPACE_ARGS --no-headers | awk '{print $1}' | grep $APP | head -1)
trap exit SIGINT

if [ -n "$CONTAINER" ] ; then
  CONTAINER_ARGS="-c $CONTAINER"
fi

echo kubectl exec $CONTAINER_ARGS $NAMESPACE_ARGS -it $POD -- $HTTP_CLIENT $URL
kubectl exec $CONTAINER_ARGS $NAMESPACE_ARGS -it $POD -- $HTTP_CLIENT $URL
