#!/bin/bash

if [ "$#" -lt 2 ]; then
  echo "usage: $0 [ -n <namespace> ] <app> "
  exit 1
fi
while getopts ":n:" opt; do
  case $opt in
    n)
      NAMESPACE=${OPTARG}
      ;;
    *)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

shift $((OPTIND-1))
APP=$1
shift

if [ -n "$NAMESPACE" ] ; then
  NAMESPACE_ARGS="-n $NAMESPACE"
fi

PATCH='{"spec":{"template":{"metadata":{"annotations":{"timestamp":"'$(date)'"}}}}}'

kubectl patch deployment $NAMESPACE_ARGS $APP -p "$PATCH" 
kubectl rollout status deployment $NAMESPACE_ARGS $APP 

