#!/bin/bash

while getopts ":n:" opt; do
  case $opt in
    n)
      NAMESPACE=${OPTARG}
      ;;
    *)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

shift $((OPTIND-1))
APP=$1
shift

if [ -n "$ns" ] ; then
  NAMESPACE_ARGS="-n $ns"
fi

if [ -n "$NAMESPACE" ] ; then
  NAMESPACE_ARGS="-n $NAMESPACE"
fi

if [ "$APP" == "" ]; then
  kubectl get po $NAMESPACE_ARGS 
else
  kubectl get po $NAMESPACE_ARGS | grep $APP 
fi

