#!/bin/sh

curl -v -k -s -S -o /dev/null -L -w  "URL:\t\t\t%{url_effective}\nHTTP Response:\t\t%{http_code}\nContent-Type:\t\t%{content_type}\nSource IP:\t\t%{local_ip}:%{local_port}\nDest IP:\t\t%{remote_ip}:%{remote_port}\nResponse size:\t\t%{size_download}\nHeader-Length:\t\t%{size_header}\nSpeed:\t\t\t%{speed_download} b/s\nDNS Lookup time:\t%{time_namelookup}\nTCP Connect:\t\t%{time_connect}\nTime pretransfer:\t%{time_pretransfer}\nTime starttransfer:\t%{time_starttransfer}\nTotal Time:\t\t%{time_total}\n" -H "Pragma: no-cache" $*
