#!/bin/bash

if [ "$1" == "-s" ]; then
  SILENT=1
  shift
fi
if [ "$#" -eq 0 ]; then
  echo "usage: $0 <app> [ namespace ]"
  exit 1
fi
APP=$1

if [[ ! -z "$2" ]]; then
 KUBE_OPTS="-n $2"
else
 KUBE_OPTS=""
fi

if [ "$CONTEXT" == "" ] ; then
  CONTEXT=$(kubectl config current-context)
fi
#HOOK=

PATCH='{"spec":{"template":{"metadata":{"annotations":{"timestamp":"'$(date)'"}}}}}'

kubectl patch deployment $APP -p "$PATCH" $KUBE_OPTS
kubectl rollout status deployment $APP $KUBE_OPTS

