#!/bin/bash

if [ "$1" == "-s" ]; then
  SILENT=1
  shift
fi
if [ "$#" -eq 0 ]; then
  echo "usage: $0 <app> [ namespace ]"
  exit 1
fi
APP=$1

if [[ ! -z "$2" ]]; then
 KUBE_OPTS="-n $2"
else
 KUBE_OPTS=""
fi

if [ "$CONTEXT" == "" ] ; then
  CONTEXT=$(kubectl config current-context)
fi
#HOOK=

PATCH='{"spec":{"template":{"metadata":{"annotations":{"timestamp":"'$(date)'"}}}}}'

# Add new clusters here
CLUSTERS=(prod production production-east1 aialik baltoro cygni jail dokriani embree foggydog grotto thanatos)

function slack() {
  MESSAGE=$1
  if [ "$SILENT" != "" ] ; then
    return
  fi

  if [[ " ${CLUSTERS[@]} " =~ " ${CONTEXT} " ]]; then
    curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$1\", \"username\": \"service-roll-bot\", \"icon_emoji\": \":boom:\"}" $HOOK
  fi
}
slack "*$USER* is rolling service *$APP* in cluster $CONTEXT"
kubectl patch deployment $APP -p "$PATCH" $KUBE_OPTS
kubectl rollout status deployment $APP $KUBE_OPTS
slack "*$USER* completed rolling service *$APP* in cluster $CONTEXT"

